add_library(sim STATIC 
    sim_101_open.cpp
    sim_102_close.cpp
    sim_103_print.cpp
    sim_104_load_batch.cpp
    sim_105_run.cpp
    sim_106_step.cpp
    sim_110_step_submit.cpp
    sim_111_step_admit.cpp
    sim_112_step_dispatch.cpp
    sim_113_step_wait_event.cpp
    sim_114_step_exit.cpp
    sim_115_step_event_occurs.cpp
    sim_116_step_activate.cpp
    sim_117_step_delete.cpp
    sim_118_step_preempt.cpp
    sim_119_step_suspend.cpp
    sim_120_job_launcher.cpp
)

